version: '3.1'
services:
  client:
    env_file: .env
    container_name: ${CLIENT_IMAGE}
    build:
      context: ./client
    image: ${CLIENT_IMAGE}:latest
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - ./client/build:/app/build
      - /app/node_modules
      - /app/build
    networks:
      - openshift
  server:
    env_file: .env
    container_name: ${SERVER_IMAGE}
    build:
      context: ./server
    image: ${SERVER_IMAGE}:latest
    ports:
      - "8081:8081"
    volumes:
      - ./server:/usr/src/app
      - ./server/dist:/usr/src/app/dist
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    networks:
      - openshift
networks:
  openshift:



