version: '3.1'
services:
  client:
    env_file: .env
    container_name: openshift-client
    image: openshift-client:latest
    command: npm run start
    build:
      context: ./client
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - openshift
  server:
    env_file: .env
    container_name: openshift-server
    image: openshift-server:latest
    command: npm run dev
    build:
      context: ./server
      target: dev
    ports:
      - "8081:8081"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - openshift
networks:
  openshift:



