version: '3.1'
services:
  client:
    env_file: .env
    build:
      context: ./client

    ports:
      - "3000:3000"
    volumes:
      - /app:app/node_modules
      - ./client:/app/node_modules

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - ./backend:/node_modules
      - /usr/src/app:/usr/src/app/node_modules


