apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-server
  labels:
    app: openshift-server
    sandbox: chelsea-angelena-dev
    chelsea-angelena-dev: openshift-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-server
  template:
    metadata:
      labels:
        app: openshift-server
    spec:
      containers:
      - name: openshift-server
        image: default-route-openshift-image-registry.apps.sandbox-m3.1530.p1.openshiftapps.com/chelsea-angelena-dev/openshift-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          protocol: TCP