name: Deployment

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      
      - name: create .env file
        run: cp .env.example .env

      - name: build-images
        run: make build




        # ...deployment-specific steps
      
      # - name: push-client-image

      # - name: build-server-image
      
      # - name: push-server-image

      # - name: apply-client

      # - name: apply-server